# Enable the Traefik dependency
traefik:
  enabled: true

  # Global settings
  globalArguments:
    - "--global.checknewversion=false"
    - "--global.sendanonymoususage=false"

  # Configure Traefik to use your provider
  providers:
    kubernetesCRD:
      enabled: true
      namespaces: []  # All namespaces
    kubernetesIngress:
      enabled: true
      namespaces: []  # All namespaces

  # Configure ports
  ports:
    web:
      port: 8000
      exposedPort: 80
      protocol: TCP
    websecure:
      port: 8443
      exposedPort: 443
      protocol: TCP
      tls:
        enabled: true  # SSL termination at Traefik level
    metrics:
      port: 9100
      exposedPort: 9100
      protocol: TCP

  # Configure Service - NLB with client IP preservation
  service:
    enabled: true
    type: LoadBalancer
    annotations:
      # NLB type specification
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      
      # Client IP preservation - IMPORTANT
      service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: "preserve_client_ip.enabled=true"
      
      # Header forwarding configurations
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
      
      # Extra: cross-zone load balancing for high availability (recommended)
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

  # Configure Traefik Dashboard
  ingressRoute:
    dashboard:
      enabled: true
      annotations: {}
      entryPoints: ["websecure"]

  # Disable persistent storage since we're not using Let's Encrypt directly
  persistence:
    enabled: false

  # Deploy with default middlewares
  deployment:
    enabled: true
    replicas: 2
    # For HA, use anti-affinity
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - traefik
              topologyKey: kubernetes.io/hostname

  # Resources limits and requests
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"

  # Enable metrics
  metrics:
    prometheus:
      enabled: true

  # Additional Traefik arguments
  additionalArguments:
    - "--log.level=INFO"
    - "--accesslog=true"
    - "--accesslog.format=json"
    # If you're using Proxy Protocol with NLB
    - "--entrypoints.web.proxyprotocol.trustedips=0.0.0.0/0"
    - "--entrypoints.websecure.proxyprotocol.trustedips=0.0.0.0/0"

# Custom Middleware definitions
middleware:
  - name: compress
    namespace: default
    spec:
      compress: {}
  
  - name: secured-headers
    namespace: default
    spec:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
  
  - name: redirect-to-https
    namespace: default
    spec:
      redirectScheme:
        scheme: https
        permanent: true

# Custom IngressRoute examples
ingressRoutes:
  - name: redirect-http
    namespace: default
    entryPoints: ["web"]
    routes:
      - match: HostRegexp(`{host:.+}`)
        kind: Rule
        services:
          - name: noop@internal
            kind: TraefikService
        middlewares:
          - name: redirect-to-https
            namespace: default

# Custom TraefikService examples
traefikServices:
  - name: weighted-service
    namespace: default
    spec:
      weighted:
        services:
          - name: service-v1
            port: 80
            weight: 80
          - name: service-v2
            port: 80
            weight: 20

  - name: mirrored-service
    namespace: default
    spec:
      mirroring:
        name: production-service
        port: 80
        mirrors:
          - name: test-service
            port: 80
            percent: 10
